# ============================================================
# AŞAĞIDAKİ BLOĞU mevcut icon_assets.py dosyasının EN SONUNA ekle
# (yani info_icon_bytes() fonksiyonundan sonra).
# Dosyanın başındaki "import base64" zaten var, tekrar eklemene gerek yok.
# ============================================================

LOCKED_ICON_B64 = (
    "iVBORw0KGgoAAAANSUhEUgAAAfQAAALWCAYAAACwWmEqAAAQp0lEQVR4nO3dO3YbRxqAUXgOdzKJY0UOtCYlxjLg"
    "xGtS4Eixk9nLRLRoSiTxqH7U1/emkoBCo09/+qtxgNMJAAAAAAAAAAAAAAAAAAAAvvtl6wVc68uX3//aeg0AHNOf"
    "f/7x29Zr+Mhugy7gAOzVHgO/q6CLOACz2UvcNw+6iANQsWXcNwu6kANQtUXYVw+6kANwFGuG/T9rPdHpJOYAHMua"
    "3VtlQhdyAI5u6Wl98QldzAFg+R4uGnQxB4DvluziIlvuSy3427dvfy/xuADwlk+fPv26xOOO3oIfHvSRMRdwAPZm"
    "ZOBHRn1o0EfEXMQBmMWIuI+K+rCgPxpzIQdgVo+GfUTUnx59gEcJOQCze27ZUvfbrzHkU+73TudiDkDJvV0bccv6"
    "4aCLOQB8t1XUH7qHfs+TCzkAR3HPFvy999NX/S53MQfgSNbs3t1Bv3U6F3MAjujW/t279X5X0MUcAK63RtRX3XIH"
    "AJZxc9BN5wBwu6Wn9EUndDEHgO+W7OJNQb/lfwtiDgA/uqWPt3TXPXQACFgk6KZzAHjbEp28Ougjf+ccALjOtf0d"
    "PqGbzgHgY6N76R46AARcFXTb7QCwnWs6PHRCt90OANcb2U1b7gAQIOgAEPBh0N0/B4DtfdTjYRO6++cAcLtR/bTl"
    "DgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4A"
    "AYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGC"
    "DgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4A"
    "AYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGC"
    "DgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4A"
    "AYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGC"
    "DgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4A"
    "AYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGC"
    "DgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4A"
    "AYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGC"
    "DgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4A"
    "AYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGC"
    "DgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4A"
    "AYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGC"
    "DgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4A"
    "AYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4AAYIOAAGC"
    "DgABgg4AAYIOAAGCDgABgg4AAYIOAAGCDgABgg4CAYUH/9OnTr6MeCwCOYlQ/Pwz6n3/+8duIJwIA7vdRj225"
    "A0CAoANAwNCgu48OANcb2c2rgu4+OgBs55oO23IHgIDhQbftDgAfG93Lq4Nu2x0A1ndtfxfZcjelA8Dbluike+gA"
    "EHBT0G/ZdjelA8CPbunjLd1ddEIXdQD4bsku3hz0Wz8cJ+oAcHsPb+2te+gAEHBX0E3pAHC9pafz0+mBCV3UAeBj"
    "a8T8dFp5y13UATiSNbv3y6MP8OXL73/d8+++ffv296PPDQB7dG/IH/lW1ocn9Huf3LQOQNEWMT+dBm25izoAbBfz"
    "0+l0enr0AR71/OJtwQMwqz0MqA/fQ3/p3vvpLwk7ALMYEfJRv2Y6NOin05ioPxN3APZm5DQ+8qfJhwf9dBob9ZcE"
    "HoC1LbWdPjLmp9NCQX+2VNgBYFajQ/5s0S+WWWrRADCjJbu4+DfFiToALN/DRbfcX7MFD8DRrDXYrvpd7qZ1AI5k"
    "ze6tOqG/ZFoHoGqLAXazoD8TdgAqttyJ3jzoL4k7ALPZy+3kXQX9JXEHYK/2EvGXdhv01wQegK3sMeAAAAAAAAAA"
    "AAAAAAAAsKD/AykxZ1GSX9rHAAAAAElFTkSuQmCC"
)


def locked_icon_bytes():
    """Soluk/kilitli kart ikonunun PNG bayt verisini döndürür.

    Geçersiz (o an oynanamayacak) kartlar için, kartın gerçek görseli yerine
    bu tek tip soluk/kilitli görsel gösterilir.
    """
    return base64.b64decode(LOCKED_ICON_B64)
  
